/**
 * Export Hardhat-compiled ABIs + deployed addresses into the Next.js app.
 *
 * Reads:
 *   artifacts/contracts/ShadowFundVault.sol/ShadowFundVault.json
 *   artifacts/contracts/ShadowFundShareToken.sol/ShadowFundShareToken.json
 *   artifacts/contracts/AaveUSDCVault.sol/AaveUSDCVault.json
 *   artifacts/contracts/FixedYieldVault.sol/FixedYieldVault.json
 *   artifacts/contracts/ISubVault.sol/ISubVault.json
 *   deployments/arbitrumSepolia.json
 *
 * Writes:
 *   lib/shadow-fund-abi.ts  — typed ABI consts
 *   (updates lib/contracts.ts inline)
 */

import * as fs from "fs";
import * as path from "path";

const ROOT = path.join(__dirname, "..");
const ARTIFACTS = path.join(ROOT, "artifacts/contracts");
const DEPLOYMENTS = path.join(ROOT, "deployments/arbitrumSepolia.json");
const ABI_OUT = path.join(ROOT, "lib/shadow-fund-abi.ts");
const CONTRACTS_OUT = path.join(ROOT, "lib/contracts.ts");

function readAbi(contractPath: string, contractName: string): unknown[] {
  const artifactPath = path.join(
    ARTIFACTS,
    `${contractPath}/${contractName}.json`
  );
  if (!fs.existsSync(artifactPath)) {
    console.warn(`Artifact not found: ${artifactPath} — skipping`);
    return [];
  }
  const json = JSON.parse(fs.readFileSync(artifactPath, "utf-8")) as { abi: unknown[] };
  return json.abi;
}

function main() {
  const vaultAbi       = readAbi("ShadowFundVault.sol", "ShadowFundVault");
  const shareAbi       = readAbi("ShadowFundShareToken.sol", "ShadowFundShareToken");
  const aaveUsdcAbi    = readAbi("AaveUSDCVault.sol", "AaveUSDCVault");
  const fixedAbi       = readAbi("FixedYieldVault.sol", "FixedYieldVault");
  const subVaultAbi    = readAbi("ISubVault.sol", "ISubVault");

  const abiContent = `/**
 * AUTO-GENERATED by scripts/export-abi.ts
 * Do not edit manually — run \`npm run export-abi\` to regenerate.
 */

export const shadowFundVaultAbi = ${JSON.stringify(vaultAbi, null, 2)} as const;

export const shadowFundShareTokenAbi = ${JSON.stringify(shareAbi, null, 2)} as const;

export const aaveUsdcVaultAbi = ${JSON.stringify(aaveUsdcAbi, null, 2)} as const;

export const fixedYieldVaultAbi = ${JSON.stringify(fixedAbi, null, 2)} as const;

export const subVaultAbi = ${JSON.stringify(subVaultAbi, null, 2)} as const;
`;

  fs.writeFileSync(ABI_OUT, abiContent, "utf-8");
  console.log(`Wrote ABIs → ${ABI_OUT}`);

  if (!fs.existsSync(DEPLOYMENTS)) {
    console.log("No deployments/arbitrumSepolia.json found — skipping address update.");
    console.log("Deploy first with `npm run deploy:arb`, then re-run `npm run export-abi`.");
    return;
  }

  const deployment = JSON.parse(fs.readFileSync(DEPLOYMENTS, "utf-8")) as {
    contracts: {
      ShadowFundVault: string;
      AaveUSDCVault?: string;
      FixedYieldVault?: string;
    };
  };

  let contractsContent = fs.readFileSync(CONTRACTS_OUT, "utf-8");

  const shadowBlock = `
  /** AaveUSDCVault — sub-vault supplying USDC to Aave v3 */
  AAVE_USDC_VAULT: "${deployment.contracts.AaveUSDCVault ?? ""}",
  /** FixedYieldVault — sub-vault accruing fixed 8% APY from reward pool */
  FIXED_YIELD_VAULT: "${deployment.contracts.FixedYieldVault ?? ""}",
  /** ShadowFundVault — meta-vault allocating across the 2 sub-vaults */
  SHADOW_FUND_VAULT: "${deployment.contracts.ShadowFundVault}",`;

  if (contractsContent.includes("SHADOW_FUND_VAULT")) {
    contractsContent = contractsContent.replace(
      /\/\*\* (ShadowFund price oracle|AaveUSDCVault)[\s\S]*?SHADOW_FUND_VAULT: "0x[0-9a-fA-F]*",/,
      shadowBlock.trim()
    );
  } else {
    contractsContent = contractsContent.replace(
      /} as const;/,
      `${shadowBlock}\n} as const;`
    );
  }

  fs.writeFileSync(CONTRACTS_OUT, contractsContent, "utf-8");
  console.log(`Updated addresses → ${CONTRACTS_OUT}`);
  console.log(`  AaveUSDCVault:    ${deployment.contracts.AaveUSDCVault ?? "(missing)"}`);
  console.log(`  FixedYieldVault:  ${deployment.contracts.FixedYieldVault ?? "(missing)"}`);
  console.log(`  ShadowFundVault:  ${deployment.contracts.ShadowFundVault}`);
}

main();
