/**
 * Export Hardhat-compiled ABIs + deployed addresses into the Next.js app.
 *
 * Reads:
 *   artifacts/contracts/ShadowFundVault.sol/ShadowFundVault.json
 *   artifacts/contracts/PriceOracle.sol/PriceOracle.json
 *   artifacts/contracts/ShadowFundShareToken.sol/ShadowFundShareToken.json
 *   deployments/arbitrumSepolia.json
 *
 * Writes:
 *   lib/shadow-fund-abi.ts  — typed ABI consts
 *   (updates lib/contracts.ts inline)
 */

import * as fs from "fs";
import * as path from "path";

const ROOT = path.join(__dirname, "..");
const ARTIFACTS = path.join(ROOT, "artifacts/contracts");
const DEPLOYMENTS = path.join(ROOT, "deployments/arbitrumSepolia.json");
const ABI_OUT = path.join(ROOT, "lib/shadow-fund-abi.ts");
const CONTRACTS_OUT = path.join(ROOT, "lib/contracts.ts");

function readAbi(contractPath: string, contractName: string): unknown[] {
  const artifactPath = path.join(
    ARTIFACTS,
    `${contractPath}/${contractName}.json`
  );
  if (!fs.existsSync(artifactPath)) {
    console.warn(`Artifact not found: ${artifactPath} — skipping`);
    return [];
  }
  const json = JSON.parse(fs.readFileSync(artifactPath, "utf-8")) as { abi: unknown[] };
  return json.abi;
}

function main() {
  // Load ABIs
  const vaultAbi    = readAbi("ShadowFundVault.sol", "ShadowFundVault");
  const oracleAbi   = readAbi("PriceOracle.sol", "PriceOracle");
  const shareAbi    = readAbi("ShadowFundShareToken.sol", "ShadowFundShareToken");

  // Write lib/shadow-fund-abi.ts
  const abiContent = `/**
 * AUTO-GENERATED by scripts/export-abi.ts
 * Do not edit manually — run \`npm run export-abi\` to regenerate.
 */

export const shadowFundVaultAbi = ${JSON.stringify(vaultAbi, null, 2)} as const;

export const priceOracleAbi = ${JSON.stringify(oracleAbi, null, 2)} as const;

export const shadowFundShareTokenAbi = ${JSON.stringify(shareAbi, null, 2)} as const;
`;

  fs.writeFileSync(ABI_OUT, abiContent, "utf-8");
  console.log(`Wrote ABIs → ${ABI_OUT}`);

  // Load deployment addresses (if available)
  if (!fs.existsSync(DEPLOYMENTS)) {
    console.log("No deployments/arbitrumSepolia.json found — skipping address update.");
    console.log("Deploy first with `npm run deploy:arb`, then re-run `npm run export-abi`.");
    return;
  }

  const deployment = JSON.parse(fs.readFileSync(DEPLOYMENTS, "utf-8")) as {
    contracts: { PriceOracle: string; ShadowFundVault: string };
  };

  // Update lib/contracts.ts — append or replace the ShadowFund block
  let contractsContent = fs.readFileSync(CONTRACTS_OUT, "utf-8");

  const shadowBlock = `
  /** ShadowFund price oracle (Chainlink wrapper for ETH/BTC/LINK) */
  PRICE_ORACLE: "${deployment.contracts.PriceOracle}",
  /** ShadowFundVault — main confidential vault contract */
  SHADOW_FUND_VAULT: "${deployment.contracts.ShadowFundVault}",`;

  if (contractsContent.includes("SHADOW_FUND_VAULT")) {
    // Replace existing entries
    contractsContent = contractsContent.replace(
      /\/\*\* ShadowFund price oracle[\s\S]*?SHADOW_FUND_VAULT: "0x[0-9a-fA-F]+",/,
      shadowBlock.trim()
    );
  } else {
    // Append before closing brace
    contractsContent = contractsContent.replace(
      /} as const;/,
      `${shadowBlock}\n} as const;`
    );
  }

  fs.writeFileSync(CONTRACTS_OUT, contractsContent, "utf-8");
  console.log(`Updated addresses → ${CONTRACTS_OUT}`);
  console.log(`  PriceOracle:     ${deployment.contracts.PriceOracle}`);
  console.log(`  ShadowFundVault: ${deployment.contracts.ShadowFundVault}`);
}

main();
